version: '3'

services:
  db:
    image: postgres
    ports:
      - "54320:5432"

  django:
    build:
      context: .
      dockerfile: Dockerfile-django
    depends_on:
      - db
    volumes:
      - ./:/app
    ports:
      - "8080:8000"