FROM python:3

ARG APPDIR=/app

RUN true \
    && groupadd app \
        --gid 1000 \
    && useradd app \
        --gid 1000 \
        --uid 1000 \
        --create-home \
        --home-dir $APPDIR

COPY requirements.txt .
RUN apt-get update && pip install psycopg2-binary
RUN pip install -r requirements.txt

USER app
WORKDIR $APPDIR