FROM python:3

ENV APPDIR=/app
WORKDIR $APPDIR

ADD . $APPDIR

RUN apt-get update && apt-get install \
  -y --no-install-recommends python3 python3-virtualenv

RUN python3 -m venv venv
RUN . venv/bin/activate
COPY requirements.txt .
RUN pip install -r requirements.txt
